version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./client/jest.config.js:/app/jest.config.js
      - ./client/jsconfig.json:/app/jsconfig.json
      - ./client/src:/app/src
      - ./client/public:/app/public

    ports:
      - 8081:3000

  serverstrapi:
    build:
      context: ./serverstrapi
      dockerfile: Dockerfile
    volumes:
      - ./serverstrapi/config:/server/config
      - ./serverstrapi/src:/server/src
      - ./serverstrapi/package.json:/server/package.json
      - ./serverstrapi/.env:/server/.env
      - ./serverstrapi/public/uploads:/server/public/uploads
    ports:
      - 3001:1337
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:14.5
    restart: always
    env_file:
      - .env
    ports:
      - 4001:5432
    volumes:
      - ./okr-db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 5001:8080

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - client
      - serverstrapi
